version: "3.9"

services:
  logging_service:
    build: ./logging_service
    container_name: logging_service
    ports:
      - "8002:8002"

  counter_service:
    build: ./counter_service
    container_name: counter_service
    ports:
      - "8003:8003"

  facade_service:
    build: ./facade_service
    container_name: facade_service
    ports:
      - "8001:8001"
    depends_on:
      - logging_service
      - counter_service